[[constraint]]
  name = "github.com/uber/jaeger-client-go"
  version = "2.11.x"

[[constraint]]
  name = "github.com/apache/thrift"
  version = "0.10.0"

[prune]
  go-tests = true
  unused-packages = true
