// Code generated by elegen. DO NOT EDIT.
// Source: go.aporeto.io/elemental (templates/model.gotpl)

package gaia

import (
	"fmt"

	"github.com/globalsign/mgo/bson"
	"github.com/mitchellh/copystructure"
	"go.aporeto.io/elemental"
)

// NodeUID represents the model of a nodeuid
type NodeUID struct {
	// The node identifier.
	ID string `json:"ID,omitempty" msgpack:"ID,omitempty" bson:"-" mapstructure:"ID,omitempty"`

	// The network address of the node described by the NodeUID.
	NetworkAddress string `json:"networkAddress,omitempty" msgpack:"networkAddress,omitempty" bson:"-" mapstructure:"networkAddress,omitempty"`

	ModelVersion int `json:"-" msgpack:"-" bson:"_modelversion"`
}

// NewNodeUID returns a new *NodeUID
func NewNodeUID() *NodeUID {

	return &NodeUID{
		ModelVersion: 1,
	}
}

// GetBSON implements the bson marshaling interface.
// This is used to transparently convert ID to MongoDBID as ObectID.
func (o *NodeUID) GetBSON() (any, error) {

	if o == nil {
		return nil, nil
	}

	s := &mongoAttributesNodeUID{}

	return s, nil
}

// SetBSON implements the bson marshaling interface.
// This is used to transparently convert ID to MongoDBID as ObectID.
func (o *NodeUID) SetBSON(raw bson.Raw) error {

	if o == nil {
		return nil
	}

	s := &mongoAttributesNodeUID{}
	if err := raw.Unmarshal(s); err != nil {
		return err
	}

	return nil
}

// BleveType implements the bleve.Classifier Interface.
func (o *NodeUID) BleveType() string {

	return "nodeuid"
}

// DeepCopy returns a deep copy if the NodeUID.
func (o *NodeUID) DeepCopy() *NodeUID {

	if o == nil {
		return nil
	}

	out := &NodeUID{}
	o.DeepCopyInto(out)

	return out
}

// DeepCopyInto copies the receiver into the given *NodeUID.
func (o *NodeUID) DeepCopyInto(out *NodeUID) {

	target, err := copystructure.Copy(o)
	if err != nil {
		panic(fmt.Sprintf("Unable to deepcopy NodeUID: %s", err))
	}

	*out = *target.(*NodeUID)
}

// Validate valides the current information stored into the structure.
func (o *NodeUID) Validate() error {

	errors := elemental.Errors{}
	requiredErrors := elemental.Errors{}

	if len(requiredErrors) > 0 {
		return requiredErrors
	}

	if len(errors) > 0 {
		return errors
	}

	return nil
}

// SpecificationForAttribute returns the AttributeSpecification for the given attribute name key.
func (*NodeUID) SpecificationForAttribute(name string) elemental.AttributeSpecification {

	if v, ok := NodeUIDAttributesMap[name]; ok {
		return v
	}

	// We could not find it, so let's check on the lower case indexed spec map
	return NodeUIDLowerCaseAttributesMap[name]
}

// AttributeSpecifications returns the full attribute specifications map.
func (*NodeUID) AttributeSpecifications() map[string]elemental.AttributeSpecification {

	return NodeUIDAttributesMap
}

// ValueForAttribute returns the value for the given attribute.
// This is a very advanced function that you should not need but in some
// very specific use cases.
func (o *NodeUID) ValueForAttribute(name string) any {

	switch name {
	case "ID":
		return o.ID
	case "networkAddress":
		return o.NetworkAddress
	}

	return nil
}

// NodeUIDAttributesMap represents the map of attribute for NodeUID.
var NodeUIDAttributesMap = map[string]elemental.AttributeSpecification{
	"ID": {
		AllowedChoices: []string{},
		ConvertedName:  "ID",
		Description:    `The node identifier.`,
		Exposed:        true,
		Name:           "ID",
		Type:           "string",
	},
	"NetworkAddress": {
		AllowedChoices: []string{},
		ConvertedName:  "NetworkAddress",
		Description:    `The network address of the node described by the NodeUID.`,
		Exposed:        true,
		Name:           "networkAddress",
		Type:           "string",
	},
}

// NodeUIDLowerCaseAttributesMap represents the map of attribute for NodeUID.
var NodeUIDLowerCaseAttributesMap = map[string]elemental.AttributeSpecification{
	"id": {
		AllowedChoices: []string{},
		ConvertedName:  "ID",
		Description:    `The node identifier.`,
		Exposed:        true,
		Name:           "ID",
		Type:           "string",
	},
	"networkaddress": {
		AllowedChoices: []string{},
		ConvertedName:  "NetworkAddress",
		Description:    `The network address of the node described by the NodeUID.`,
		Exposed:        true,
		Name:           "networkAddress",
		Type:           "string",
	},
}

type mongoAttributesNodeUID struct {
}
