# Model
model:
  rest_name: buckettopentry
  resource_name: buckettopentries
  entity_name: BucketTopEntry
  package: agrias
  group: applicationinsight/buckets
  description: Represent a top entry within a bucket.
  detached: true

# Attributes
attributes:
  v1:
  - name: name
    description: Name of the entry.
    type: string
    exposed: true
    read_only: true
    autogenerated: true

  - name: occurrences
    description: Number of times the entry showed up.
    type: integer
    exposed: true
    read_only: true
    autogenerated: true
