# Model
model:
  rest_name: urlreputation
  resource_name: urlreputations
  entity_name: URLReputation
  package: karl
  group: pc/pandb
  description: Represents the URL reputation information.
  detached: true

# Attributes
attributes:
  v1:
  - name: URL
    description: The IP address or FQDN.
    type: string
    exposed: true
    read_only: true
    autogenerated: true
    omit_empty: true

  - name: categories
    description: The categories codes related to the risk level.
    type: list
    exposed: true
    subtype: integer
    read_only: true
    autogenerated: true
    omit_empty: true

  - name: evidence
    description: The evidence related to the risk level.
    type: list
    exposed: true
    subtype: string
    read_only: true
    autogenerated: true
    omit_empty: true

  - name: riskLevel
    description: The associated IP/FQDN risk level.
    type: string
    exposed: true
    read_only: true
    autogenerated: true
    omit_empty: true
