# Model
model:
  rest_name: firewallendpoint
  resource_name: firewallendpoints
  entity_name: FirewallEndpoint
  package: ngfw ## ???
  group: ngfw/firewall ## ???
  description: |-
    TODO
  
  # Attributes
attributes:
  v1:
  - name: endpointID
    description: The AWS subnet ID.
    type: string
    exposed: true
    stored: true
    read_only: true 
    
  - name: endpointStatus
    description: The status of the firewall endpoint.
    type: enum
    exposed: true
    stored: true
    read_only: true # Not sure if this correct. Only the backend can set the status.
    allowed_choices:
    - Creating
    - Accepted
    default_value: Creating
    transient: true # ???
    autogenerated: true # ???

  - name: endpointStatusReason
    description: The AWS status reason
    type: string
    exposed: true
    stored: true
    read_only: true 

  - name: subnetID
    description: The AWS subnet ID.
    type: string
    exposed: true
    stored: true

