# Model
model:
  rest_name: bucketdestinationport
  resource_name: bucketdestinationports
  entity_name: BucketDestinationPort
  package: agrias
  group: applicationinsight/buckets
  description: |-
    Holds the destination ports of flows across 24 hours (beginning of a day to
    the end).
  aliases:
  - bktdestport
  extends:
  - '@identifiable-stored'
  - '@migratable'
  - '@namespaced'
  - '@zoned'

# Indexes
indexes:
- - namespace
  - date

# Attributes
attributes:
  v1:
  - name: date
    description: The date that the bucket tracks.
    type: string
    exposed: true
    stored: true
    required: true
    creation_only: true
    example_value: "2022-05-09"

  - name: ports
    description: Ports encountered and number of occurrences seen.
    type: external
    exposed: true
    subtype: map[string][]bucketentry
    stored: true
    omit_empty: true
    extensions:
      refMode: pointer

  - name: topPorts
    description: List of most encountered ports, sorted by occurrences.
    type: refList
    exposed: true
    subtype: buckettopentry
    read_only: true
    autogenerated: true
    omit_empty: true
    extensions:
      refMode: pointer
