# Model
model:
  rest_name: connectionsrequest
  resource_name: connectionsrequests
  entity_name: ConnectionsRequest
  package: guy
  group: core/enforcer
  description: Initiates a request for a PUs current connections.

# Attributes
attributes:
  v1:
  - name: requestID
    description: Unique ID generated for each request.
    type: string
    exposed: true
    read_only: true
    autogenerated: true

  - name: refreshID
    description: Contains the refresh ID set by processing unit refresh event.
    type: string
    exposed: true
    required: true
    example_value: xxxx-xxxx-xxxx