name: build-go
on:
  push:
    branches:
      - master
  pull_request:

defaults:
  run:
    shell: bash

env:
  GO111MODULE: on

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go:
          - 1.18
          - 1.17
          - 1.16
          - 1.15
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: setup-for-go-115
        if: ${{ matrix.go == 1.15 }}
        run: |
          # stay on an old version of golangci-lint which still builds against 1.15
          #
          # see release notes and this file for detail:
          # https://github.com/golangci/golangci-lint/blob/v1.43.0/.github/workflows/pr.yml#L67-70
          go get github.com/golangci/golangci-lint/cmd/golangci-lint@v1.42.1

      - name: setup-for-new-go
        if: ${{ matrix.go != 1.15 }}
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      - name: setup
        run: |
          go version
          go install github.com/securego/gosec/cmd/gosec@latest
          #go install golang.org/x/tools/cmd/cover@latest
          go install github.com/axw/gocov/gocov@master
          go install github.com/AlekSi/gocov-xml@latest
          go install go.aporeto.io/elemental/cmd/elegen@master
          go install go.aporeto.io/regolithe/cmd/rego@master

      - name: build
        run: |
          make

#      - name: coverage
#        uses: codacy/codacy-coverage-reporter-action@v1
#        with:
#          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
#
#          # a comma-separated list
#          coverage-reports: "./coverage.xml"
